default_model: gpt-4o
max_threads: 4

optimizer_config:
  enable_optimizer: true
  sample_size: 5  
  validation_sample_size: 3  
  optimizer_model: gpt-4o

datasets:
  papers:
    type: file
    path: ./papers_dataset.json

operations:
  - name: extract_sample_prep
    type: map
    model: gpt-4o
    output:
      schema:
        CleavageAgent: list[string]
        AlkylationReagent: list[string]
        ReductionReagent: list[string]
        Depletion: list[string]
        Label: list[string]
        ConcentrationOfCompound: list[string]
        Compound: list[string]
        Modification: list[string]
        SpikedCompound: list[string]
        SyntheticPeptide: list[string]
    prompt: |
      Extract sample preparation information from this proteomics paper.
      
      Paper: {{ input.filename }}
      {% if input.methods %}Methods: {{ input.methods }}{% endif %}
      {% if input.supplementary_information %}Supplementary: {{ input.supplementary_information }}{% endif %}
      
      Extract ALL variations of:
      - CleavageAgent: digestion enzymes (e.g., "trypsin", "digested with trypsin", "Lys-C", "chymotrypsin")
      - AlkylationReagent: alkylation agents (e.g., "iodoacetamide", "IAA", "chloroacetamide", "CAA")
      - ReductionReagent: reduction agents (e.g., "DTT", "dithiothreitol", "TCEP", "beta-mercaptoethanol")
      - Depletion: depletion methods (e.g., "albumin depletion", "IgG depletion", "ProteoMiner")
      - Label: labeling methods (e.g., "TMT", "TMT10plex", "iTRAQ", "SILAC", "label-free")
      - ConcentrationOfCompound: concentrations with units (e.g., "10 mg", "2 mM", "50 µg")
      - Compound: molecular compounds (e.g., "protein", "peptide", "phosphopeptide", "albumin")
      - Modification: PTMs (e.g., "phosphorylation", "ubiquitination", "acetylation", "carbamidomethylation")
      - SpikedCompound: spiked standards (e.g., "BSA", "yeast enolase", "UPS1", "UPS2")
      - SyntheticPeptide: synthetic standards (e.g., "heavy labeled peptides", "isotope-labeled standards")
      
      Extract BOTH full names AND abbreviations (e.g., "DTT" AND "dithiothreitol").
      Return JSON only, no markdown. Empty list if field not found.
    
    gleaning:
      num_rounds: 2
      validation_prompt: |
        Check if extraction missed: (1) cleavage enzyme (CRITICAL - 95% of papers), (2) reduction/alkylation reagents (80%+ of papers), (3) labeling method, (4) both full names and abbreviations.
        Common mistakes: enzyme mentioned but not extracted, only abbreviation without full name.
        Return: {"passes_validation": true/false, "critical_omissions": [...], "suggestions": [...]}

  - name: unnest_cleavage
    type: unnest
    unnest_key: CleavageAgent
    keep_empty: true

  - name: resolve_cleavage
    type: resolve
    blocking_keys:
      - CleavageAgent
    blocking_threshold: 0.85
    comparison_model: gpt-4o-mini
    comparison_prompt: |
      Are these the same enzyme?
      Agent 1: "{{ input1.CleavageAgent }}"
      Agent 2: "{{ input2.CleavageAgent }}"
      
      Equivalences: "trypsin"="trypsin digestion", "Lys-C"="LysC"="endoproteinase Lys-C", "Glu-C"="V8 protease"
      Return "True" if same enzyme, "False" if different.
    
    embedding_model: text-embedding-3-small
    resolution_model: gpt-4o-mini
    resolution_prompt: |
      Standardize these cleavage agents (prefer enzyme name only):
      {% for entry in inputs %}{{ entry.CleavageAgent }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Examples: ["trypsin","trypsin digestion"]→"trypsin", ["Lys-C","LysC"]→"Lys-C"
      Return ONLY the canonical name.
    
    output:
      schema:
        canonical_cleavage: string

  - name: unnest_alkylation
    type: unnest
    unnest_key: AlkylationReagent
    keep_empty: true

  - name: resolve_alkylation
    type: resolve
    blocking_keys:
      - AlkylationReagent
    blocking_threshold: 0.85
    comparison_model: gpt-4o-mini
    comparison_prompt: |
      Are these the same alkylation reagent?
      Reagent 1: "{{ input1.AlkylationReagent }}"
      Reagent 2: "{{ input2.AlkylationReagent }}"
      
      Equivalences: "iodoacetamide"="IAA", "chloroacetamide"="CAA"="2-chloroacetamide"
      Return "True" if same compound, "False" if different.
    
    embedding_model: text-embedding-3-small
    resolution_model: gpt-4o-mini
    resolution_prompt: |
      Standardize these alkylation reagents (prefer full name with abbreviation):
      {% for entry in inputs %}{{ entry.AlkylationReagent }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Examples: ["iodoacetamide","IAA"]→"iodoacetamide (IAA)", ["chloroacetamide","CAA"]→"chloroacetamide (CAA)"
      Return ONLY the canonical name.
    
    output:
      schema:
        canonical_alkylation: string

  - name: unnest_label
    type: unnest
    unnest_key: Label
    keep_empty: true

  - name: resolve_label
    type: resolve
    blocking_keys:
      - Label
    blocking_threshold: 0.85
    comparison_model: gpt-4o-mini
    comparison_prompt: |
      Are these the same labeling method?
      Label 1: "{{ input1.Label }}"
      Label 2: "{{ input2.Label }}"
      
      Equivalences: "TMT"="tandem mass tag", "iTRAQ"="isobaric tag", "SILAC"="stable isotope labeling", "label-free"="LFQ"
      Different: "TMT10plex"≠"TMT11plex", "iTRAQ 4-plex"≠"iTRAQ 8-plex"
      Generic "TMT" matches specific plexes. Return "True" if same, "False" if different.
    
    embedding_model: text-embedding-3-small
    resolution_model: gpt-4o-mini
    resolution_prompt: |
      Standardize these labels (prefer specific plex notation):
      {% for entry in inputs %}{{ entry.Label }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Examples: ["TMT","TMT10plex"]→"TMT10plex", ["iTRAQ","iTRAQ 4-plex"]→"iTRAQ 4-plex", ["label-free","LFQ"]→"label-free"
      Return ONLY the canonical name.
    
    output:
      schema:
        canonical_label: string

  - name: aggregate_sample_prep
    type: reduce
    reduce_key:
      - filename
    output:
      schema:
        unique_cleavage_agents: list[string]
        unique_alkylation_reagents: list[string]
        unique_reduction_reagents: list[string]
        unique_labels: list[string]
        unique_modifications: list[string]
        unique_depletions: list[string]
        unique_compounds: list[string]
    prompt: |
      Aggregate and deduplicate sample preparation for: {{ reduce_key.filename }}
      
      Cleavage: {% for doc in inputs %}{% if doc.canonical_cleavage %}{{ doc.canonical_cleavage }}, {% endif %}{% endfor %}
      Alkylation: {% for doc in inputs %}{% if doc.canonical_alkylation %}{{ doc.canonical_alkylation }}, {% endif %}{% endfor %}
      Labels: {% for doc in inputs %}{% if doc.canonical_label %}{{ doc.canonical_label }}, {% endif %}{% endfor %}
      Reduction: {% for doc in inputs %}{% for r in doc.ReductionReagent %}{{ r }}, {% endfor %}{% endfor %}
      Modifications: {% for doc in inputs %}{% for m in doc.Modification %}{{ m }}, {% endfor %}{% endfor %}
      
      Return deduplicated JSON with unique canonical values only.

pipeline:
  steps:
    - name: sample_prep_pipeline
      input: papers
      operations:
        - extract_sample_prep
        - unnest_cleavage
        - resolve_cleavage
        - unnest_alkylation
        - resolve_alkylation
        - unnest_label
        - resolve_label
        - aggregate_sample_prep

  output:
    type: file
    path: ./output/sample_prep_complete.json
    intermediate_dir: ./checkpoints