default_model: gpt-4o
max_threads: 4

optimizer_config:
  enable_optimizer: true
  sample_size: 5  
  validation_sample_size: 3  
  optimizer_model: gpt-4o

datasets:
  papers:
    type: file
    path: ./papers_dataset.json

operations:
  - name: extract_separation
    type: map
    model: gpt-4o
    output:
      schema:
        Separation: list[string]
        Chromatography: list[string]
        FractionationMethod: list[string]
        FractionationFraction: list[string]
        FractionIdentifier: list[string]
        NumberOfFractions: list[string]
        EnrichmentMethod: list[string]
        Bait: list[string]
        FlowRateChromatogram: list[string]
        GradientTime: list[string]
        Time: list[string]
        Temperature: list[string]
    prompt: |
      Extract separation and chromatography information from this proteomics paper.
      
      Paper: {{ input.filename }}
      {% if input.methods %}Methods: {{ input.methods }}{% endif %}
      {% if input.supplementary_information %}Supplementary: {{ input.supplementary_information }}{% endif %}
      
      Extract ALL variations of:
      - Separation: pre-MS separation (e.g., "SDS-PAGE", "SCX chromatography", "reversed-phase", "IEF", "SEC")
      - Chromatography: chromatography systems (e.g., "SCX", "strong cation exchange", "RP", "C18", "UPLC", "HILIC")
      - FractionationMethod: fractionation techniques (e.g., "high-pH RP", "SCX fractionation", "offline fractionation")
      - FractionationFraction: fraction details (e.g., "12 fractions", "24 fractions")
      - FractionIdentifier: fraction IDs (e.g., "fraction 1", "F1-F12")
      - NumberOfFractions: total fractions (e.g., "12", "24", "96")
      - EnrichmentMethod: enrichment techniques (e.g., "IMAC", "immobilized metal affinity chromatography", "TiO2", "phosphopeptide enrichment")
      - Bait: affinity baits (e.g., "anti-FLAG", "protein A", "streptavidin")
      - FlowRateChromatogram: flow rates (e.g., "300 nL/min", "0.3 µL/min")
      - GradientTime: gradient duration (e.g., "120 min", "90 min gradient")
      - Time: time durations (e.g., "overnight", "6 hours", "30 minutes")
      - Temperature: temperatures (e.g., "37°C", "room temperature", "4°C")
      
      Note: Chromatography methods appear in BOTH Separation AND Chromatography fields.
      Return JSON only, no markdown. Empty list if field not found.
    
    gleaning:
      num_rounds: 1
      validation_prompt: |
        Check if extraction missed: (1) chromatography methods, (2) enrichment methods, (3) gradient times, (4) common terms (SDS-PAGE, SCX, C18, IMAC, TiO2).
        Return: {"passes_validation": true/false, "critical_omissions": [...], "next_round_instructions": "..."}

  - name: unnest_chromatography
    type: unnest
    unnest_key: Chromatography
    keep_empty: true

  - name: resolve_chromatography
    type: resolve
    blocking_keys:
      - Chromatography
    blocking_threshold: 0.85
    comparison_model: gpt-4o-mini
    comparison_prompt: |
      Are these the same chromatography method?
      Method 1: "{{ input1.Chromatography }}"
      Method 2: "{{ input2.Chromatography }}"
      
      Equivalences: "SCX"="strong cation exchange", "RP"="reversed-phase", "UPLC"="UHPLC"="nano-LC", "HILIC"="hydrophilic interaction chromatography"
      Different: C18≠C8≠C4 (column types), SCX≠WCX, RP≠normal-phase, C18≠"reversed-phase"
      Return "True" if same technique, "False" if different.
    
    embedding_model: text-embedding-3-small
    resolution_model: gpt-4o
    resolution_prompt: |
      Standardize these chromatography methods (prefer full name with specific details):
      {% for entry in inputs %}{{ entry.Chromatography }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Examples: ["SCX","strong cation exchange"]→"strong cation exchange chromatography (SCX)", ["RP","reversed-phase"]→"reversed-phase chromatography (RP)", ["C18"]→"C18 reversed-phase column"
      Return ONLY the canonical name.
    
    output:
      schema:
        canonical_chromatography: string

  - name: unnest_enrichment
    type: unnest
    unnest_key: EnrichmentMethod
    keep_empty: true

  - name: resolve_enrichment
    type: resolve
    blocking_keys:
      - EnrichmentMethod
    blocking_threshold: 0.85
    comparison_model: gpt-4o-mini
    comparison_prompt: |
      Are these the same enrichment method?
      Method 1: "{{ input1.EnrichmentMethod }}"
      Method 2: "{{ input2.EnrichmentMethod }}"
      
      Equivalences: "IMAC"="immobilized metal affinity chromatography", "TiO2"="titanium dioxide", "IP"="immunoprecipitation"="antibody enrichment"
      Different: IMAC≠TiO2≠IP, "phosphopeptide enrichment"≠"IMAC"
      Return "True" if same technique, "False" if different.
    
    embedding_model: text-embedding-3-small
    resolution_model: gpt-4o
    resolution_prompt: |
      Standardize these enrichment methods (prefer full name with abbreviation):
      {% for entry in inputs %}{{ entry.EnrichmentMethod }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Examples: ["IMAC","immobilized metal affinity chromatography"]→"immobilized metal affinity chromatography (IMAC)", ["TiO2","titanium dioxide"]→"titanium dioxide (TiO2) enrichment"
      Return ONLY the canonical name.
    
    output:
      schema:
        canonical_enrichment: string

  - name: aggregate_separation
    type: reduce
    reduce_key:
      - filename
    model: gpt-4o
    output:
      schema:
        unique_chromatography_methods: list[string]
        unique_enrichment_methods: list[string]
        gradient_times: list[string]
        flow_rates: list[string]
        number_of_fractions: list[string]
        separation_techniques: list[string]
        fractionation_methods: list[string]
        baits: list[string]
        temperatures: list[string]
    prompt: |
      Aggregate and deduplicate separation/chromatography for: {{ reduce_key.filename }}
      
      {% for doc in inputs %}
      Chromatography: {% if doc.canonical_chromatography %}{{ doc.canonical_chromatography }}{% endif %}
      Enrichment: {% if doc.canonical_enrichment %}{{ doc.canonical_enrichment }}{% endif %}
      Gradient: {% for g in doc.GradientTime %}{{ g }}, {% endfor %}
      Flow rate: {% for f in doc.FlowRateChromatogram %}{{ f }}, {% endfor %}
      Fractions: {% for n in doc.NumberOfFractions %}{{ n }}, {% endfor %}
      Separation: {% for s in doc.Separation %}{{ s }}, {% endfor %}
      Fractionation: {% for fm in doc.FractionationMethod %}{{ fm }}, {% endfor %}
      Baits: {% for b in doc.Bait %}{{ b }}, {% endfor %}
      Temperature: {% for t in doc.Temperature %}{{ t }}, {% endfor %}
      {% endfor %}
      
      Return deduplicated JSON with unique values for all fields.

pipeline:
  steps:
    - name: separation_pipeline
      input: papers
      operations:
        - extract_separation
        - unnest_chromatography
        - resolve_chromatography
        - unnest_enrichment
        - resolve_enrichment
        - aggregate_separation

  output:
    type: file
    path: ./output/separation_complete.json
    intermediate_dir: ./checkpoints