default_model: gpt-4o
max_threads: 4

optimizer_config:
  enable_optimizer: true
  sample_size: 5  
  validation_sample_size: 3  
  optimizer_model: gpt-4o

datasets:
  papers:
    type: file
    path: ./papers_dataset.json

operations:
  - name: extract_clinical_info
    type: map
    model: gpt-4o
    output:
      schema:
        Disease: list[string]
        DiseaseTreatment: list[string]
        CellLine: list[string]
        CellType: list[string]
        CellPart: list[string]
        Treatment: list[string]
        SampleTreatment: list[string]
        Staining: list[string]
        GrowthRate: list[string]
        SamplingTime: list[string]
        BMI: list[string]
        AnatomicSiteTumor: list[string]
        OriginSiteDisease: list[string]
        TumorCellularity: list[string]
        TumorGrade: list[string]
        TumorStage: list[string]
        TumorSize: list[string]
        TumorSite: list[string]
    prompt: |
      Extract clinical and experimental context from this proteomics paper.
      This could be CLINICAL (patient samples) or LAB (cell culture/animals). Adapt accordingly.
      
      Paper: {{ input.filename }}
      {% if input.methods %}Methods: {{ input.methods }}{% endif %}
      {% if input.supplementary_information %}Supplementary: {{ input.supplementary_information }}{% endif %}
      
      Extract ALL variations and IMMEDIATELY STANDARDIZE them:
      - Disease: disease names in standardized format "Full Name (ABBR)" (e.g., "Alzheimer's disease (AD)", "breast cancer", "lung squamous cell carcinoma (LSCC)")
      - DiseaseTreatment: disease treatments (e.g., "chemotherapy", "immunotherapy", "drug name")
      - CellLine: cell line names in standard format (e.g., "HeLa", "HEK293", "MCF-7", "A549")
      - CellType: cell types - ALWAYS CONVERT markers to cell type names (e.g., "CD8+"→"CD8+ T cells", "CD4+"→"CD4+ T cells", "FOXP3+"→"regulatory T cells", "CD20+"→"B cells", "CD19+"→"B cells", "CD33+"→"neutrophils", "CD11c+"→"dendritic cells", "CD11b+"→"myeloid cells")
      - CellPart: cellular components (e.g., "nucleus", "cytoplasm", "mitochondria", "membrane")
      - Treatment: ONLY experimental interventions that ALTER biological state
        INCLUDE: drug treatments (e.g., "MG-132 treatment", "TSA treatment", "curcumin treatment"), biological stimuli (e.g., "heat shock", "LPS stimulation", "starvation"), therapeutic antibodies (e.g., "anti-CD40 antibody treatment"), cell/tissue treatments (e.g., "diphtheria toxin administration", "clodronate liposomes")
        EXCLUDE: administration routes (e.g., "retro-orbital injection", "intraperitoneal injection", "i.v.", "i.p."), analytical methods (e.g., "flow cytometry", "PCR", "genotyping", "western blot", "immunoblotting"), sample preparation (e.g., "immunoprecipitation", "lysis", "centrifugation", "washing"), general procedures (e.g., "adoptive transfer" without specifying what, "transfection" as a method)
      - SampleTreatment: sample processing methods (e.g., "FFPE", "snap frozen", "fresh frozen", "fixed")
      - Staining: staining methods (e.g., "Coomassie blue", "H&E", "silver stain")
      - GrowthRate: growth conditions (e.g., "exponential phase", "OD600 = 0.6")
      - SamplingTime: time points (e.g., "ZT6", "day 1", "T0", "T24")
      - BMI: body mass index (e.g., "BMI 25-30", "BMI > 30")
      - AnatomicSiteTumor: tumor anatomical location (e.g., "primary tumor", "left lobe")
      - OriginSiteDisease: disease origin site (e.g., "primary site")
      - TumorCellularity: tumor cellularity (e.g., "80%", ">70% tumor cells")
      - TumorGrade: tumor grade (e.g., "Grade 1", "Grade 2", "well-differentiated", "poorly differentiated")
      - TumorStage: tumor stage (e.g., "Stage I", "T3", "N1", "M0", "TNM")
      - TumorSize: tumor size (e.g., "2 cm", "5 cm diameter")
      - TumorSite: tumor site (e.g., "primary site", "metastatic lesion")
      
      CRITICAL RULES:
      1. Convert ALL cell markers to cell type names in the extraction step
      2. Filter OUT analytical methods and injection routes from Treatment field
      3. Standardize cell lines: "HEK 293"→"HEK293", "MCF7"/"MCF-7"→"MCF-7"
      4. Standardize diseases: provide full name with abbreviation if common
      5. For cell types, prefer: "CD8+ T cells" over just "T cells", "regulatory T cells (Tregs)" over "Tregs"
      
      Return JSON only, no markdown. Empty list if field not found.
    
    gleaning:
      num_rounds: 2
      validation_prompt: |
        Check if extraction missed:
        For CLINICAL studies: 
          (1) disease with full name+abbreviation (e.g., "colorectal cancer (CRC)")
          (2) tumor stage/grade/cellularity
          (3) IHC markers converted to cell types (CD8→T cells, CD20→B cells)
        
        For LAB studies:
          (1) cell lines with standard format
          (2) experimental treatments - MUST distinguish:
              YES: actual treatments (drugs, stimuli) like "MG-132 treatment", "heat shock", "poly(I:C) treatment"
              NO: administration methods like "retro-orbital injection", "intraperitoneal injection"
              NO: analytical methods like "flow cytometry", "PCR", "genotyping"
              NO: sample prep like "immunoprecipitation", "lysis"
          (3) cell type markers MUST be converted:
              CD4+ → CD4+ T cells
              CD8+ → CD8+ T cells
              FOXP3+ → regulatory T cells (Tregs)
              CD19+ or CD20+ → B cells
              CD11c+ → dendritic cells
              CD11b+ → myeloid cells
        
        Common mistakes: 
          - Markers not converted: "CD8+", "FOXP3+" appearing as-is
          - Analytical methods in treatments: "flow cytometry", "PCR"
          - Injection routes in treatments: "retro-orbital injection"
          - Sample prep in treatments: "immunoprecipitation"
        
        Return: {"passes_validation": true/false, "critical_omissions": [...], "suggestions": [...]}

  - name: unnest_disease
    type: unnest
    unnest_key: Disease
    keep_empty: true

  - name: resolve_disease
    type: resolve
    blocking_keys:
      - Disease
    blocking_threshold: 0.80
    comparison_model: gpt-4o-mini
    comparison_prompt: |
      Are these the same disease?
      Disease 1: "{{ input1.Disease }}"
      Disease 2: "{{ input2.Disease }}"
      
      Equivalences: "Alzheimer's disease"="AD"="Alzheimer", "breast cancer"="BC", "colorectal cancer"="CRC", "lung cancer"="LC"
      Different: breast cancer ≠ lung cancer, Alzheimer's ≠ Parkinson's
      Return "True" if same disease, "False" if different.
    
    embedding_model: text-embedding-3-small
    resolution_model: gpt-4o-mini
    resolution_prompt: |
      Standardize these disease names (prefer full name with common abbreviation):
      {% for entry in inputs %}{{ entry.Disease }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Examples: ["Alzheimer's disease","AD","Alzheimer"]→"Alzheimer's disease (AD)", ["breast cancer","BC"]→"breast cancer", ["CRC","colorectal cancer"]→"colorectal cancer (CRC)"
      Return ONLY the canonical name.
    
    output:
      schema:
        canonical_disease: string

  - name: unnest_cell_line
    type: unnest
    unnest_key: CellLine
    keep_empty: true

  - name: resolve_cell_line
    type: resolve
    blocking_keys:
      - CellLine
    blocking_threshold: 0.85
    comparison_model: gpt-4o-mini
    comparison_prompt: |
      Are these the same cell line?
      Cell line 1: "{{ input1.CellLine }}"
      Cell line 2: "{{ input2.CellLine }}"
      
      Equivalences: "HEK293"="HEK-293"="HEK 293", "MCF7"="MCF-7", "A549"="A-549"
      Different: HeLa ≠ HEK293, MCF-7 ≠ MCF-10A
      Return "True" if same cell line, "False" if different.
    
    embedding_model: text-embedding-3-small
    resolution_model: gpt-4o-mini
    resolution_prompt: |
      Standardize these cell line names (prefer standard format without spaces):
      {% for entry in inputs %}{{ entry.CellLine }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Examples: ["HEK293","HEK-293","HEK 293"]→"HEK293", ["MCF7","MCF-7"]→"MCF-7", ["A549","A-549"]→"A549"
      Return ONLY the canonical name.
    
    output:
      schema:
        canonical_cell_line: string

  - name: unnest_cell_type
    type: unnest
    unnest_key: CellType
    keep_empty: true

  - name: resolve_cell_type
    type: resolve
    blocking_keys:
      - CellType
    blocking_threshold: 0.80
    comparison_model: gpt-4o-mini
    comparison_prompt: |
      Are these the same cell type?
      Cell type 1: "{{ input1.CellType }}"
      Cell type 2: "{{ input2.CellType }}"
      
      Equivalences: "CD8+ T cells"="CD8 T cells"="cytotoxic T cells"="CTLs", "CD4+ T cells"="CD4 T cells"="helper T cells", "regulatory T cells"="Tregs"="FOXP3+ T cells", "B cells"="CD19+ B cells"="CD20+ B cells", "dendritic cells"="DCs"="CD11c+ cells", "macrophages"="CD11b+ macrophages", "neutrophils"="CD33+ cells"
      Different: CD8+ T cells ≠ CD4+ T cells, B cells ≠ T cells, macrophages ≠ dendritic cells
      Return "True" if same cell type, "False" if different.
    
    embedding_model: text-embedding-3-small
    resolution_model: gpt-4o-mini
    resolution_prompt: |
      Standardize these cell type names (prefer full descriptive name with marker):
      {% for entry in inputs %}{{ entry.CellType }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Examples: ["CD8+ T cells","CD8 T cells","cytotoxic T cells"]→"CD8+ T cells", ["regulatory T cells","Tregs","FOXP3+ T cells"]→"regulatory T cells (Tregs)", ["B cells","CD19+ B cells","CD20+ B cells"]→"B cells", ["dendritic cells","DCs"]→"dendritic cells"
      Return ONLY the canonical name.
    
    output:
      schema:
        canonical_cell_type: string

  - name: unnest_treatment
    type: unnest
    unnest_key: Treatment
    keep_empty: true

  - name: resolve_treatment
    type: resolve
    blocking_keys:
      - Treatment
    blocking_threshold: 0.85
    comparison_model: gpt-4o-mini
    comparison_prompt: |
      Are these the same treatment?
      Treatment 1: "{{ input1.Treatment }}"
      Treatment 2: "{{ input2.Treatment }}"
      
      Equivalences: "LPS"="lipopolysaccharide"="LPS stimulation", "heat shock"="heat stress", "MG-132"="MG132"="proteasome inhibitor MG-132", "TSA"="trichostatin A"
      Different: LPS ≠ poly(I:C), heat shock ≠ cold shock, MG-132 ≠ TSA
      Return "True" if same treatment, "False" if different.
    
    embedding_model: text-embedding-3-small
    resolution_model: gpt-4o-mini
    resolution_prompt: |
      Standardize these treatment names (prefer specific compound/stimulus with common abbreviation):
      {% for entry in inputs %}{{ entry.Treatment }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Examples: ["LPS","lipopolysaccharide","LPS stimulation"]→"lipopolysaccharide (LPS)", ["MG-132","MG132","proteasome inhibitor MG-132"]→"MG-132", ["TSA","trichostatin A"]→"trichostatin A (TSA)"
      Return ONLY the canonical name.
    
    output:
      schema:
        canonical_treatment: string

  - name: aggregate_clinical_data
    type: reduce
    reduce_key:
      - filename
    model: gpt-4o
    output:
      schema:
        unique_diseases: list[string]
        unique_cell_lines: list[string]
        unique_cell_types: list[string]
        unique_treatments: list[string]
        unique_disease_treatments: list[string]
        unique_cell_parts: list[string]
        tumor_stages: list[string]
        tumor_grades: list[string]
        tumor_cellularity: list[string]
        tumor_sizes: list[string]
        tumor_sites: list[string]
        sample_treatments: list[string]
        staining_methods: list[string]
        growth_rates: list[string]
        sampling_times: list[string]
        bmi_values: list[string]
    prompt: |
      Aggregate and deduplicate clinical/experimental data for: {{ reduce_key.filename }}
      
      {% for doc in inputs %}
      Diseases: {% if doc.canonical_disease %}{{ doc.canonical_disease }}{% elif doc.Disease %}{% for d in doc.Disease %}{{ d }}, {% endfor %}{% endif %}
      Cell lines: {% if doc.canonical_cell_line %}{{ doc.canonical_cell_line }}{% elif doc.CellLine %}{% for cl in doc.CellLine %}{{ cl }}, {% endfor %}{% endif %}
      Cell types: {% if doc.canonical_cell_type %}{{ doc.canonical_cell_type }}{% elif doc.CellType %}{% for ct in doc.CellType %}{{ ct }}, {% endfor %}{% endif %}
      Treatments: {% if doc.canonical_treatment %}{{ doc.canonical_treatment }}{% elif doc.Treatment %}{% for t in doc.Treatment %}{{ t }}, {% endfor %}{% endif %}
      Disease treatments: {% for dt in doc.DiseaseTreatment %}{{ dt }}, {% endfor %}
      Cell parts: {% for cp in doc.CellPart %}{{ cp }}, {% endfor %}
      Tumor stages: {% for s in doc.TumorStage %}{{ s }}, {% endfor %}
      Tumor grades: {% for g in doc.TumorGrade %}{{ g }}, {% endfor %}
      Tumor cellularity: {% for c in doc.TumorCellularity %}{{ c }}, {% endfor %}
      Tumor sizes: {% for ts in doc.TumorSize %}{{ ts }}, {% endfor %}
      Tumor sites: {% for site in doc.TumorSite %}{{ site }}, {% endfor %}
      Sample treatments: {% for st in doc.SampleTreatment %}{{ st }}, {% endfor %}
      Staining: {% for sm in doc.Staining %}{{ sm }}, {% endfor %}
      Growth rates: {% for gr in doc.GrowthRate %}{{ gr }}, {% endfor %}
      Sampling times: {% for stime in doc.SamplingTime %}{{ stime }}, {% endfor %}
      BMI: {% for bmi in doc.BMI %}{{ bmi }}, {% endfor %}
      {% endfor %}
      
      IMPORTANT RULES:
      1. REMOVE from treatments any:
         - Administration routes: "retro-orbital injection", "intraperitoneal injection", "i.v.", "i.p."
         - Analytical methods: "flow cytometry", "PCR", "genotyping", "western blot", "immunoblotting", "mass spectrometry"
         - Sample prep: "immunoprecipitation", "lysis", "centrifugation", "transfection" (as method), "washing"
         - Generic procedures without specific treatment: "adoptive transfer", "immunization" (unless specific)
      
      2. DEDUPLICATE using canonical values when available, otherwise deduplicate similar entries
      
      3. KEEP as treatments:
         - Actual drug treatments: "MG-132 treatment", "TSA treatment", "curcumin treatment"
         - Biological stimuli: "heat shock", "LPS stimulation", "poly(I:C) treatment"
         - Therapeutic interventions: "diphtheria toxin administration", "anti-CD40 antibody treatment", "clodronate liposomes"
      
      Return deduplicated JSON with unique values for all fields, properly filtered.

pipeline:
  steps:
    - name: clinical_experimental_pipeline
      input: papers
      operations:
        - extract_clinical_info
        - unnest_disease
        - resolve_disease
        - unnest_cell_line
        - resolve_cell_line
        - unnest_cell_type
        - resolve_cell_type
        - unnest_treatment
        - resolve_treatment
        - aggregate_clinical_data

  output:
    type: file
    path: ./output/clinical_experimental_complete.json
    intermediate_dir: ./checkpoints