default_model: gpt-4o
max_threads: 4

optimizer_config:
  enable_optimizer: true
  sample_size: 5  
  validation_sample_size: 3  
  optimizer_model: gpt-4o

datasets:
  papers:
    type: file
    path: ./papers_dataset.json

operations:
  - name: extract_biological_info
    type: map
    model: gpt-4o
    output:
      schema:
        Organism: list[string]
        Strain: list[string]
        Age: list[string]
        Sex: list[string]
        OrganismPart: list[string]
        MaterialType: list[string]
        Specimen: list[string]
        AncestryCategory: list[string]
        DevelopmentalStage: list[string]
        Genotype: list[string]
        GeneticModification: list[string]
        NumberOfBiologicalReplicates: list[string]
        Treatment: list[string]
    prompt: |
      You are extracting biological sample metadata from proteomics research papers to enable standardized data cataloging and reproducibility. Your task is to carefully read the provided text and identify all explicitly mentioned biological information across 13 categories. This information is critical for researchers to understand experimental conditions and compare datasets.
      
      Paper: {{ input.filename }}
      {% if input.methods %}
      Methods section:
      """{{ input.methods }}"""
      {% endif %}
      {% if input.supplementary_information %}
      Supplementary information:
      """{{ input.supplementary_information }}"""
      {% endif %}
      
      Extract ALL mentions of the following categories. ONLY extract information that is explicitly stated in the text - do not infer, assume, or generate any information:
      
      - Organism: scientific AND common names (e.g., "Mus musculus", "mouse", "mice", "human", "Homo sapiens")
      - Strain: organism strain/line (e.g., "C57BL/6", "HeLa", "Swiss-Webster", "wild-type")
      - Age: age descriptions - capture ALL variations (e.g., "8-12 weeks", "adult", "P7", "6 months old", "three-week-old", "3 weeks", "8 weeks", "eight weeks")
      - Sex: biological sex (e.g., "male", "female", "both sexes", "mixed")
      - OrganismPart: tissues/organs/anatomical parts (e.g., "brain", "liver", "hippocampus", "cortex")
      - MaterialType: biological sample type (e.g., "tissue", "plasma", "cells", "CSF", "serum", "urine")
      - Specimen: specimen preparation type (e.g., "biopsy", "fresh frozen", "FFPE", "cultured cells")
      - AncestryCategory: ancestry/ethnicity for human studies (e.g., "European", "Asian", "African American")
      - DevelopmentalStage: developmental stage (e.g., "embryonic", "adult", "juvenile", "postnatal day 7")
      - Genotype: genetic background (e.g., "wild-type", "knockout", "APP/PS1", "heterozygous")
      - GeneticModification: genetic modifications (e.g., "CRISPR knockout", "transgenic", "lentiviral transduction")
      - NumberOfBiologicalReplicates: sample size or number of replicates (e.g., "n=5", "three animals per group", "5 biological replicates")
      - Treatment: experimental treatments or interventions applied to biological samples (e.g., "fasting", "overnight feeding", "fed ad libitum", "drug treatment", "LPS stimulation", "insulin injection", "high-fat diet", "vehicle control", "glucose stimulation", "serum starvation")
      
        **IMPORTANT FOR TREATMENT**: This field is for biological/dietary/pharmacological interventions applied to the organisms/samples:
        - INCLUDE: "overnight feeding", "fasting", "fed ad libitum", "high-fat diet", "normal diet", "drug administration"
        - INCLUDE: Stimulation/challenge: "LPS stimulation", "glucose challenge", "insulin injection"  
        - DO NOT include: sample preparation methods (e.g., "trypsin digestion", "reduction with DTT")
        - DO NOT include: analytical procedures (e.g., "MS analysis", "Western blot")
      
      CRITICAL INSTRUCTIONS TO AVOID HALLUCINATIONS:
      - ONLY extract information that is explicitly and clearly stated in the provided text
      - Extract information EXACTLY as written in the text - do not paraphrase or modify
      - For Age: if written as words (e.g., "three-week-old"), extract BOTH the word form AND numeric form (e.g., "three-week-old" AND "3 weeks")
      - If you are uncertain whether information belongs to a category, do NOT include it
      - If you cannot find explicit mention of information for a category, return an empty list [] for that category
      - Do NOT make any assumptions, inferences, or educated guesses beyond what is directly stated
      - Do NOT generate or invent any information that is not present in the text
      - If a term is ambiguous or unclear, do NOT include it
      - Capture all variations and synonyms only if they explicitly appear (e.g., both "mouse" and "Mus musculus" if both are written in the text)
      - When in doubt, leave the category empty rather than guessing
      
      OUTPUT FORMAT INSTRUCTIONS:
      Return your response as a valid JSON object using the exact category names listed above as keys.
      - Each key must map to a list of strings containing the extracted information
      - If no information was found for a category, use an empty list: []
      - Do NOT include any markdown formatting (no ```json or ``` blocks)
      - Do NOT include any explanatory text, comments, or notes
      - Do NOT include any text before or after the JSON object
      - Return ONLY the raw JSON object, nothing else
      
      Example format:
      {
        "Organism": ["Mus musculus", "mouse"],
        "Strain": ["C57BL/6"],
        "Age": ["8 weeks", "eight weeks"],
        "Sex": [],
        "OrganismPart": ["brain", "hippocampus"],
        "MaterialType": ["tissue"],
        "Specimen": [],
        "AncestryCategory": [],
        "DevelopmentalStage": [],
        "Genotype": ["wild-type"],
        "GeneticModification": [],
        "NumberOfBiologicalReplicates": ["n=5"],
        "Treatment": ["fasting"]
      }
    
    gleaning:
      num_rounds: 2
      validation_prompt: |
        You are a quality control reviewer checking whether biological metadata extraction from a proteomics paper is complete and accurate. Your goal is to identify any information that was clearly stated in the text but missed in the extraction, while being careful not to encourage hallucination.
        
        Review the original paper text and the extracted metadata carefully. Check specifically for these CRITICAL categories that are commonly present in proteomics papers:
        
        1. **Organism names**: Almost every proteomics paper mentions the organism studied
           - Look for: scientific names (e.g., "Mus musculus", "Homo sapiens") or common names (e.g., "mouse", "mice", "human")
           - Check: abstract, introduction, methods sections
        
        2. **Tissues, organs, or anatomical parts**: The biological source of samples
           - Look for: specific tissues (e.g., "brain", "liver"), organs, anatomical regions (e.g., "hippocampus", "cortex")
           - These are usually in methods or results sections
        
        3. **Sample sizes or biological replicates**: Essential for reproducibility
           - Look for: "n=X", "X animals", "X samples", "X biological replicates", "X mice per group"
           - Check: methods section, figure legends, results
        
        4. **Strain information**: Important for mouse/rat studies
           - Look for: strain names like "C57BL/6", "Wistar", cell lines like "HeLa", "HEK293"
        
        5. **Age, sex, or developmental stage**: Key experimental variables
           - Age: "8 weeks", "adult", "P7", "postnatal day 7", "three-week-old"
           - Sex: "male", "female", "both sexes"
        
        6. **Treatment or intervention information** (CRITICAL for intervention studies):
           - Look for feeding/fasting: "overnight feeding", "fed ad libitum", "fasted", "feeding", "diet"
           - Look for stimulation: "LPS stimulation", "glucose challenge", "insulin injection"
           - Look for drug treatments: specific drug names, "treatment", "administered"
           - Check: methods, abstract, results sections - treatments are often mentioned multiple times
           - Common phrases: "overnight", "ad libitum", "fasting", "stimulation", "challenge", "injection", "treated with"
        
        7. **Age format completeness** (CRITICAL):
           - If age appears in word form (e.g., "three-week-old", "eight weeks old"), check if the numeric equivalent was also extracted
           - Should have BOTH forms: word form (as written) AND numeric form (e.g., "3 weeks", "8 weeks")
        
        IMPORTANT VALIDATION PRINCIPLES:
        - Only flag information that is CLEARLY and EXPLICITLY stated in the original text
        - Do NOT suggest adding information based on assumptions or typical practices
        - Do NOT suggest information that might be implied but is not directly stated
        - Focus on information that was stated but missed, not information that should have been stated
        - Be specific: cite the exact text where missed information appears
        
        Provide your assessment as a JSON object with the following structure:
        {
          "passes_validation": true or false,
          "critical_omissions": ["list specific missed information with exact quotes from text, e.g., 'Organism: paper states Mus musculus in methods but was not extracted'"],
          "missing_treatment": true or false,
          "treatment_evidence": "exact quote from text showing treatment if missing_treatment is true, otherwise empty string",
          "age_needs_numeric_conversion": true or false,
          "age_word_forms_found": ["list word-form ages found in text that need numeric conversion"],
          "confidence_issues": ["list any extractions that seem uncertain or potentially hallucinated"],
          "next_round_instructions": "specific, detailed guidance on what explicitly stated information to extract in the next round, with exact quotes or locations in the text. If validation passes, return empty string."
        }
        
        Remember: Only flag truly missing information that is explicitly present in the text. Do not encourage adding information that is not clearly stated.
    
    validate:
      - 'len(output["Organism"]) > 0'

  - name: unnest_organism
    type: unnest
    unnest_key: Organism
    keep_empty: true

  - name: resolve_organism
    type: resolve
    blocking_keys:
      - Organism
    blocking_threshold: 0.85
    embedding_model: text-embedding-3-small
    comparison_prompt: |
      Compare these two organism mentions to determine if they refer to the same species.
      
      Organism 1: "{{ input1.Organism }}"
      Organism 2: "{{ input2.Organism }}"
      
      Consider these as the SAME organism if:
      - They are the same scientific name (e.g., "Mus musculus" and "Mus musculus")
      - One is the scientific name and the other is the common name for the same species (e.g., "Mus musculus" and "mouse")
      - They are different common names for the same species (e.g., "mouse" and "mice")
      
      Common organism mappings:
      - "mouse", "mice", "Mus musculus" → same organism
      - "human", "humans", "Homo sapiens" → same organism
      - "rat", "rats", "Rattus norvegicus" → same organism
      
      Return ONLY "True" if they refer to the same organism, or "False" if they are different organisms.
      Do not include any explanation or additional text.
    resolution_model: gpt-4o-mini
    output:
      schema:
        canonical_organism: string
    resolution_prompt: |
      You are standardizing organism names to their scientific nomenclature for database consistency.
      
      Given these organism mentions from the same paper:
      {% for entry in inputs %}{{ entry.Organism }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Standardization rules:
      - ALWAYS prefer the scientific name over common names
      - Use proper binomial nomenclature with genus capitalized and species lowercase
      
      Standard mappings you MUST follow:
      - ["mouse", "mice", "Mus musculus"] → "Mus musculus"
      - ["human", "humans", "Homo sapiens"] → "Homo sapiens"  
      - ["rat", "rats", "Rattus norvegicus"] → "Rattus norvegicus"
      - ["zebrafish", "Danio rerio"] → "Danio rerio"
      - ["fruit fly", "Drosophila melanogaster"] → "Drosophila melanogaster"
      - ["yeast", "Saccharomyces cerevisiae"] → "Saccharomyces cerevisiae"
      - ["E. coli", "Escherichia coli"] → "Escherichia coli"
      
      Return ONLY the canonical scientific name, nothing else. No explanation, no additional text.
      
      Canonical organism name:

  - name: unnest_organism_part
    type: unnest
    unnest_key: OrganismPart
    keep_empty: true

  - name: resolve_organism_part
    type: resolve
    blocking_keys:
      - OrganismPart
    blocking_threshold: 0.85
    embedding_model: text-embedding-3-small
    comparison_prompt: |
      Compare these two organism part mentions to determine if they refer to the same anatomical structure.
      
      Organism Part 1: "{{ input1.OrganismPart }}"
      Organism Part 2: "{{ input2.OrganismPart }}"
      
      Consider these as the SAME organism part if:
      - They are exact matches (e.g., "brain" and "brain")
      - They are synonyms for the same structure (e.g., "brain" and "cerebrum")
      - One is an abbreviation of the other (e.g., "CSF" and "cerebrospinal fluid")
      - They differ only in plural/singular form (e.g., "cell" and "cells")
      
      Consider these as DIFFERENT if:
      - They are different anatomical structures (e.g., "brain" and "liver")
      - One is a sub-region of the other (e.g., "brain" and "hippocampus" - these should stay separate)
      
      Return ONLY "True" if they refer to the same organism part, or "False" if they are different.
      Do not include any explanation or additional text.
    resolution_model: gpt-4o-mini
    output:
      schema:
        canonical_organism_part: string
    resolution_prompt: |
      You are standardizing organism part names to preferred anatomical terminology.
      
      Given these organism part mentions from the same paper:
      {% for entry in inputs %}{{ entry.OrganismPart }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Standardization rules:
      - Prefer full anatomical terms over abbreviations
      - Use singular form
      - Use lowercase unless it's a proper anatomical term
      
      Common standardizations:
      - ["CSF", "cerebrospinal fluid"] → "cerebrospinal fluid"
      - ["cells", "cell"] → "cell"
      - ["brains", "brain"] → "brain"
      - ["livers", "liver"] → "liver"
      
      Return ONLY the canonical organism part name, nothing else. No explanation, no additional text.
      
      Canonical organism part name:

  - name: aggregate_biological_info
    type: reduce
    reduce_key:
      - filename
    optimize: true
    output:
      schema:
        unique_organisms: list[string]
        unique_organism_parts: list[string]
        strains: list[string]
        ages: list[string]
        sexes: list[string]
        material_types: list[string]
        biological_replicates: list[string]
        treatments: list[string]
    prompt: |
      You are aggregating and deduplicating biological metadata extracted from a proteomics paper.
      
      Paper: {{ reduce_key.filename }}
      
      Input data to aggregate:
      
      Organisms (canonical): {% for doc in inputs %}{% if doc.canonical_organism %}{{ doc.canonical_organism }}, {% endif %}{% endfor %}
      
      Organism parts (canonical): {% for doc in inputs %}{% if doc.canonical_organism_part %}{{ doc.canonical_organism_part }}, {% endif %}{% endfor %}
      
      Strains: {% for doc in inputs %}{% for s in doc.Strain %}{{ s }}, {% endfor %}{% endfor %}
      
      Ages: {% for doc in inputs %}{% for a in doc.Age %}{{ a }}, {% endfor %}{% endfor %}
      
      Sex: {% for doc in inputs %}{% for s in doc.Sex %}{{ s }}, {% endfor %}{% endfor %}
      
      Material Types: {% for doc in inputs %}{% for m in doc.MaterialType %}{{ m }}, {% endfor %}{% endfor %}
      
      Biological Replicates: {% for doc in inputs %}{% for r in doc.NumberOfBiologicalReplicates %}{{ r }}, {% endfor %}{% endfor %}
      
      Treatments: {% for doc in inputs %}{% for t in doc.Treatment %}{{ t }}, {% endfor %}{% endfor %}
      
      Your task:
      1. Collect all unique values for each category (remove exact duplicates)
      2. Keep all variations as separate entries (e.g., "8 weeks" and "eight weeks" are different entries)
      3. Return empty lists for categories with no data
      
      Return a JSON object with these exact keys: unique_organisms, unique_organism_parts, strains, ages, sexes, material_types, biological_replicates, treatments
      
      Each key should map to a list of unique string values found in the input data.
      
      Do NOT include any markdown formatting, explanatory text, or anything other than the raw JSON object.

pipeline:
  steps:
    - name: biological_pipeline
      input: papers
      operations:
        - extract_biological_info
        - unnest_organism
        - resolve_organism
        - unnest_organism_part
        - resolve_organism_part
        - aggregate_biological_info

  output:
    type: file
    path: ./output/biological_info_complete.json
    intermediate_dir: ./checkpoints