datasets:
  papers:
    path: ./papers_dataset.json
    type: file
default_model: gpt-4o
max_threads: 4
operations:
- model: gpt-4o
  name: aggregate_biological_info
  output:
    schema:
      ages: list[string]
      biological_replicates: list[string]
      material_types: list[string]
      sexes: list[string]
      strains: list[string]
      unique_organism_parts: list[string]
      unique_organisms: list[string]
  prompt: 'Aggregate and deduplicate biological information for: {{ reduce_key.filename
    }}


    Organisms: {% for doc in inputs %}{% if doc.canonical_organism %}{{ doc.canonical_organism
    }}, {% endif %}{% endfor %}

    Organism parts: {% for doc in inputs %}{% if doc.canonical_organism_part %}{{
    doc.canonical_organism_part }}, {% endif %}{% endfor %}

    Strains: {% for doc in inputs %}{% for s in doc.Strain %}{{ s }}, {% endfor %}{%
    endfor %}

    Ages: {% for doc in inputs %}{% for a in doc.Age %}{{ a }}, {% endfor %}{% endfor
    %}

    Sex: {% for doc in inputs %}{% for s in doc.Sex %}{{ s }}, {% endfor %}{% endfor
    %}

    Materials: {% for doc in inputs %}{% for m in doc.MaterialType %}{{ m }}, {% endfor
    %}{% endfor %}

    Replicates: {% for doc in inputs %}{% for r in doc.NumberOfBiologicalReplicates
    %}{{ r }}, {% endfor %}{% endfor %}


    Return deduplicated JSON with unique values for: unique_organisms, unique_organism_parts,
    strains, ages, sexes, material_types, biological_replicates.

    '
  reduce_key:
  - filename
  type: reduce
- blocking_keys:
  - OrganismPart
  blocking_threshold: 0.8
  comparison_model: gpt-4o-mini
  comparison_prompt: 'Are these the same organism part?

    Part 1: "{{ input1.OrganismPart }}"

    Part 2: "{{ input2.OrganismPart }}"


    Equivalences: "brain"="brains", "CSF"="cerebrospinal fluid", "RBCs"="red blood
    cells"

    Return "True" if same, "False" if different.

    '
  embedding_model: text-embedding-3-small
  model: gpt-4o
  name: resolve_organism_part
  output:
    schema:
      canonical_organism_part: string
  resolution_model: gpt-4o-mini
  resolution_prompt: 'Standardize these organism parts (prefer full form):

    {% for entry in inputs %}{{ entry.OrganismPart }}{% if not loop.last %}, {% endif
    %}{% endfor %}

    Return ONLY the canonical name.

    '
  type: resolve
- keep_empty: true
  model: gpt-4o
  name: unnest_organism_part
  type: unnest
  unnest_key: OrganismPart
- blocking_keys:
  - Organism
  blocking_threshold: 0.8
  comparison_model: gpt-4o-mini
  comparison_prompt: 'Are these the same organism?

    Organism 1: "{{ input1.Organism }}"

    Organism 2: "{{ input2.Organism }}"


    Equivalences: "mouse"="mice"="Mus musculus", "human"="Homo sapiens", "HeLa"="human"

    Return "True" if same, "False" if different.

    '
  embedding_model: text-embedding-3-small
  model: gpt-4o
  name: resolve_organism
  output:
    schema:
      canonical_organism: string
  resolution_model: gpt-4o-mini
  resolution_prompt: "Standardize these organism names (prefer scientific name):\n\
    {% for entry in inputs %}{{ entry.Organism }}{% if not loop.last %}, {% endif\
    \ %}{% endfor %}\n\nExamples: [\"mouse\",\"mice\",\"Mus musculus\"]\xE2\u2020\u2019\
    \"Mus musculus\", [\"human\",\"HeLa\"]\xE2\u2020\u2019\"Homo sapiens\"\nReturn\
    \ ONLY the canonical name.\n"
  type: resolve
- keep_empty: true
  model: gpt-4o
  name: unnest_organism
  type: unnest
  unnest_key: Organism
- gleaning:
    num_rounds: 1
    validation_prompt: 'Check if extraction missed: (1) organism names, (2) tissues/organs,
      (3) sample sizes, (4) strain/age details.

      Return: {"passes_validation": true/false, "critical_omissions": [...], "next_round_instructions":
      "..."}

      '
  model: gpt-4o
  name: extract_biological_info
  output:
    schema:
      Age: list[string]
      AncestryCategory: list[string]
      DevelopmentalStage: list[string]
      GeneticModification: list[string]
      Genotype: list[string]
      MaterialType: list[string]
      NumberOfBiologicalReplicates: list[string]
      Organism: list[string]
      OrganismPart: list[string]
      Sex: list[string]
      Specimen: list[string]
      Strain: list[string]
  prompt: 'Extract biological information from this proteomics paper.


    Paper: {{ input.filename }}

    {% if input.methods %}Methods: {{ input.methods }}{% endif %}

    {% if input.supplementary_information %}Supplementary: {{ input.supplementary_information
    }}{% endif %}


    Extract ALL mentions of:

    - Organism: scientific AND common names (e.g., "Mus musculus", "mouse", "mice")

    - Strain: organism strain/line (e.g., "C57BL/6", "HeLa", "Swiss-Webster")

    - Age: age descriptions (e.g., "8-12 weeks", "adult", "P7")

    - Sex: biological sex (e.g., "male", "female", "both sexes")

    - OrganismPart: tissues/organs (e.g., "brain", "liver", "hippocampus")

    - MaterialType: sample type (e.g., "tissue", "plasma", "cells", "CSF")

    - Specimen: specimen type (e.g., "biopsy", "fresh frozen", "FFPE")

    - AncestryCategory: ancestry/ethnicity (e.g., "European", "Asian")

    - DevelopmentalStage: developmental stage (e.g., "embryonic", "adult")

    - Genotype: genetic background (e.g., "wild-type", "knockout")

    - GeneticModification: modifications (e.g., "CRISPR knockout", "transgenic")

    - NumberOfBiologicalReplicates: sample size (e.g., "n=5", "three animals per group")


    Return JSON only, no markdown. Empty list if field not found.

    '
  type: map
  validate:
  - len(output["Organism"]) > 0
optimizer_config:
  enable_optimizer: true
  optimizer_model: gpt-4o
  sample_size: 5
  validation_sample_size: 3
pipeline:
  output:
    intermediate_dir: ./checkpoints
    path: ./output/biological_info_complete.json
    type: file
  steps:
  - input: papers
    name: biological_pipeline
    operations:
    - extract_biological_info
    - unnest_organism
    - resolve_organism
    - unnest_organism_part
    - resolve_organism_part
    - aggregate_biological_info
