default_model: gpt-5.2
max_threads: 4

model_settings:
  gpt-5.2:
    reasoning:
      effort: medium
    text:
      verbosity: low

optimizer_config:
  enable_optimizer: true
  sample_size: 5  
  validation_sample_size: 3  
  optimizer_model: gpt-5.2
  optimizer_model_settings:
    reasoning:
      effort: medium
    text:
      verbosity: low

datasets:
  papers:
    type: file
    path: ./papers_dataset.json

operations:
  - name: extract_clinical_info
    type: map
    model: gpt-5.2
    model_params:
      reasoning:
        effort: medium
      text:
        verbosity: low
    output:
      schema:
        Disease: list[string]
        DiseaseTreatment: list[string]
        CellLine: list[string]
        CellType: list[string]
        CellPart: list[string]
        GrowthRate: list[string]
        SamplingTime: list[string]
        BMI: list[string]
        AnatomicSiteTumor: list[string]
        OriginSiteDisease: list[string]
        TumorCellularity: list[string]
        TumorGrade: list[string]
        TumorStage: list[string]
        TumorSize: list[string]
        TumorSite: list[string]
    prompt: |
      You are extracting clinical and experimental context metadata from proteomics research papers.
      
      Paper: {{ input.filename }}
      
      {% if input.abstract %}
      Abstract:
      """{{ input.abstract }}"""
      {% endif %}
      
      {% if input.methods %}
      Methods:
      """{{ input.methods }}"""
      {% endif %}
      
      {% if input.supplementary %}
      Supplementary Information:
      """{{ input.supplementary }}"""
      {% endif %}
      
      CRITICAL FIRST STEP - IDENTIFY PROTEOMICS SECTIONS:
      Before extracting any annotations, you MUST:
      1. Read through ALL sections of the paper (abstract, methods, results, figures, supplementary)
      2. Identify which parts describe PROTEOMICS or MASS SPECTROMETRY experiments
      3. Look for IMPLICIT proteomics indicators including:
         - Affinity purification followed by mass spectrometry (AP-MS)
         - Tandem affinity purification (TAP) - commonly used for MS
         - Protein purification workflows that precede MS analysis
         - Immunoprecipitation (IP) followed by MS
         - Pull-down assays analyzed by MS
         - References to MS in abstract even if methods don't explicitly mention it
      4. Extract annotations from these proteomics-specific sections
      5. IGNORE sections about non-MS techniques
      
      PROTEOMICS WORKFLOW DETECTION SIGNALS:
      - Direct mentions: "mass spectrometry", "MS", "LC-MS", "proteomics"
      - Affinity purification techniques: "TAP", "AP-MS", "pull-down MS"
      - Protein identification workflows followed by unspecified analysis (assume MS if in proteomics paper)
      - Abstract mentions proteomics while methods describe protein purification
      
      The annotations you extract must describe HOW THE PROTEOMICS PART OF THE STUDY WAS PERFORMED.
      If a paper contains multiple experiment types, focus exclusively on the proteomics/mass spectrometry workflow.
      
      Extract the following clinical and experimental annotation types from proteomics sections only:
      
      - Disease: Disease state or diagnosis
      - DiseaseTreatment: Pre-treatment applied to diseased samples
      - CellLine: Name of the immortalized cell line
      - CellType: Primary cell type or lineage
      - CellPart: Subcellular compartment or fraction
      - GrowthRate: Doubling time or growth rate of cell cultures
      - SamplingTime: Time of sample collection
      - BMI: Body-Mass Index of the donor (kg/m²)
      - AnatomicSiteTumor: Anatomical location from which a tumor sample was taken
      - OriginSiteDisease: Anatomical site of disease origin
      - TumorCellularity: Percentage of tumor cells in the sample
      - TumorGrade: Histological grade
      - TumorStage: Stage of tumor 
      - TumorSize: Physical size of the tumor
      - TumorSite: Anatomical site of tumor
      
      CRITICAL EXTRACTION RULES:
      
      PROTEOMICS-ONLY EXTRACTION (HIGHEST PRIORITY):
      
      A. PROTEOMICS SECTION IDENTIFICATION:
         - First, identify all sections that describe proteomics or mass spectrometry experiments
         - Extract annotations ONLY from these proteomics-specific sections
         - DO NOT extract from sections about non-MS techniques
         - ALLOW reasonable inference when abstract mentions proteomics but methods describe protein purification
      
      B. SAMPLE DIFFERENTIATION TEST:
         - Before extracting, ask: "Is this metadata important for differentiating between proteomics samples?"
         - If NO, do not extract it
         - Focus on metadata that distinguishes one proteomics sample from another
      
      C. UTILITY TEST:
         - Before extracting, ask: "Is this metadata trivial or useful?"
         - Do NOT extract typical values used commonly across most proteomics experiments
         - Focus on metadata that provides meaningful experimental context
      
      D. BALANCED ANNOTATION APPROACH:
         - Avoid being too liberal: Don't fill with useless metadata
         - Avoid being too conservative: Don't miss key differentiating metadata
         - Apply both tests (B and C) to achieve balance
      
      E. COMPREHENSIVE PROTEOMICS SECTION REVIEW:
         - Use ALL parts of the paper that discuss proteomics
         - Some critical information only appears in results or figure captions
         - Search thoroughly across all proteomics-relevant sections before finalizing extraction
      
      1. SOURCE FIDELITY: Extract ONLY text that exists verbatim in the source material
         - MUST copy exact wording, spelling, and punctuation from the text
         - Do NOT paraphrase, rephrase, or reword anything
         - Do NOT standardize or normalize terminology
      
      2. CONTROLLED INFERENCE: Extract explicitly stated information, with LIMITED inference allowed for:
         - Standard cell line identification from nomenclature
         - DO NOT infer other annotation types without explicit mention
         - DO NOT make assumptions beyond standard nomenclature
      
      3. NO HALLUCINATION: Do NOT generate or fabricate any information
         - Every extracted annotation MUST be traceable to the proteomics sections
         - If you cannot find it in the proteomics-relevant text, do NOT include it
         - Do NOT use your background knowledge to add information beyond standard nomenclature
      
      4. NO DUPLICATES: Extract each unique annotation only ONCE
         - If the same term appears multiple times, extract it only ONCE
         - Do NOT repeat the same annotation
         - Check for uniqueness before adding to the list
         - This is critical for maintaining clean, non-redundant metadata
      
      5. VERIFY BEFORE EXTRACTION: Before extracting any annotation, verify:
         - Is this from a section describing proteomics/MS experiments OR protein purification for MS?
         - Can you point to the exact location in the proteomics text where it appears?
         - Is it written exactly as you are extracting it?
         - Does it clearly match the annotation type definition?
         - Does it pass the sample differentiation test?
         - Does it pass the utility test?
         - If you cannot answer YES to all six, do NOT extract it
      
      6. COMPLETE WORDS AND PHRASES ONLY (CRITICAL):
         - Extract entities as complete words or meaningful phrases
         - NEVER split words into individual letters or characters
         - Each extracted value must be a complete term with semantic meaning
         - Before finalizing, verify each value is a complete word or phrase
         - Single character extractions indicate a critical error
      
      7. DISEASE EXTRACTION PRINCIPLES:
         - ONLY extract diseases describing samples used in the proteomics experiment
         - Extract disease states or diagnoses of samples analyzed by MS
         - Include control disease states when both are studied
         - Do NOT extract diseases from background or introduction that are not study focus
         - Do NOT extract from cited references to other studies
         - Do NOT extract potential future applications
         - GOLDEN RULE: Only extract if proteomics samples WITH this disease are actually analyzed
         - Only extract if used in proteomics experiments
      
      8. DISEASE TREATMENT EXTRACTION PRINCIPLES:
          - Extract pre-treatments applied to diseased samples before proteomics analysis
          - Extract medical therapies or interventions applied to samples
          - Focus on treatments that differentiate proteomics samples
          - Only extract if used in proteomics experiments
      
      9. CELL LINE EXTRACTION PRINCIPLES:
         - Extract ONLY immortalized cell line names used in proteomics experiments
         - Include source information when provided with the cell line name
         - Include specific clone or variant designations when stated
         - Do NOT extract organism strain names
         - Do NOT extract primary cell types
         - Only extract if used in proteomics experiments
      
      10. CELL TYPE EXTRACTION PRINCIPLES (CRITICAL):
          - Extract COMPLETE primary cell type or lineage names as SINGLE strings
          - NEVER split cell type names into individual characters
          - Include any parenthetical information or markers stated with the cell type
          - CellType is for primary cell types or lineages (living cells)
          - Do NOT confuse with tissue or organ names
          - Only extract if used in proteomics experiments
      
      11. CELL PART EXTRACTION PRINCIPLES:
          - Extract subcellular compartments or fractions analyzed by proteomics
          - Extract organelle or cellular fraction names
          - Focus on subcellular localization information
          - Only extract if used in proteomics experiments
      
      12. GROWTH RATE EXTRACTION PRINCIPLES:
          - Extract doubling time or growth rate of cell cultures
          - Extract cell culture growth phase or condition descriptions
          - Include units when provided
          - Only extract if used in proteomics experiments
      
      13. SAMPLING TIME EXTRACTION PRINCIPLES:
          - Extract time points when proteomics samples were collected
          - Extract harvest time or collection time descriptions
          - Include units and context when provided
          - Only extract if used in proteomics experiments
      
      14. BMI EXTRACTION PRINCIPLES:
          - Extract Body-Mass Index values of donors in kg/m²
          - Include units when provided
          - Only extract if used in proteomics experiments
      
      15. TUMOR CHARACTERISTICS EXTRACTION PRINCIPLES:
          - AnatomicSiteTumor: Extract anatomical location from which tumor sample was taken for proteomics
          - OriginSiteDisease: Extract anatomical site of disease origin
          - TumorCellularity: Extract percentage of tumor cells in the proteomics sample
          - TumorGrade: Extract histological grade classifications
          - TumorStage: Extract clinical staging classifications
          - TumorSize: Extract physical size measurements of the tumor
          - TumorSite: Extract anatomical site of tumor
          - Extract exactly as reported in the proteomics sample descriptions
          - Only extract if used in proteomics experiments
      
      16. ACCURACY OVER COMPLETENESS:
          - When in doubt, do NOT extract
          - Better to miss information than extract from non-proteomics sections
          - Only extract when certain it matches the annotation type AND is from proteomics sections
          - Empty lists are PERFECTLY ACCEPTABLE if annotations are not found
      
      17. NO TEXT IN OUTPUT:
          - Return ONLY the JSON object with annotation lists
          - Do NOT include source text sections
          - Do NOT include explanations outside the JSON structure
          - Do NOT include document identifiers in output
      
      18. EMPTY RESULTS ARE OK:
          - If an annotation type is not found in the proteomics sections, return an empty list []
          - Do NOT attempt to fill in likely values
          - Do NOT extract related but different information
          - It is better to return [] than to extract incorrect information
      
      19. SPECIFICITY REQUIREMENTS:
          - Extract only information from proteomics sections that directly matches the annotation category
          - DO NOT extract tangentially related information
          - Verify category assignment is correct before including any term
          - When category assignment is ambiguous, do NOT extract
      
      20. MENTAL VERIFICATION PROCESS:
          - For each potential extraction, mentally note:
            * Is this from a proteomics/mass spectrometry section of the paper?
            * Where exactly in the proteomics section is this stated?
            * Is this the exact wording from the source?
            * Why does this qualify as this specific annotation type?
            * Is this a complete word or phrase, not a character?
            * For Disease: are proteomics samples with this disease actually analyzed?
            * Does this help differentiate proteomics samples?
            * Is this useful metadata or trivial information?
          - Only include if you can clearly answer all relevant questions
      
      21. CONTEXT-BASED EXTRACTION:
          - Pay attention to section context
          - Some terms have different meanings in different contexts
          - Extract based on functional role in the proteomics workflow
          - Consider whether the information describes proteomics samples
          - Only extract from proteomics-relevant contexts
      
      22. CLINICAL VS LABORATORY CONTEXT:
          - Some papers focus on patient samples (clinical context)
          - Some papers focus on cell culture experiments (laboratory context)
          - Some papers include both types of data
          - Extract information appropriate to the paper's actual proteomics experimental system
          - Do NOT extract clinical data from purely laboratory proteomics studies
          - Do NOT extract laboratory data from purely clinical proteomics studies
      
      Return ONLY a valid JSON object with lists of extracted values and no other text.

pipeline:
  steps:
    - name: clinical_experimental_pipeline
      input: papers
      operations:
        - extract_clinical_info

  output:
    type: file
    path: ./output/clinical_experimental_complete.json
    intermediate_dir: ./checkpoints