default_model: gpt-4o
max_threads: 4

optimizer_config:
  enable_optimizer: true
  sample_size: 5  
  validation_sample_size: 3  
  optimizer_model: gpt-4o

datasets:
  papers:
    type: file
    path: ./papers_dataset.json

operations:
  - name: extract_clinical_info
    type: map
    model: gpt-4o
    output:
      schema:
        Disease: list[string]
        DiseaseTreatment: list[string]
        CellLine: list[string]
        CellType: list[string]
        CellPart: list[string]
        Treatment: list[string]
        SampleTreatment: list[string]
        Staining: list[string]
        GrowthRate: list[string]
        SamplingTime: list[string]
        BMI: list[string]
        AnatomicSiteTumor: list[string]
        OriginSiteDisease: list[string]
        TumorCellularity: list[string]
        TumorGrade: list[string]
        TumorStage: list[string]
        TumorSize: list[string]
        TumorSite: list[string]
    prompt: |
      Extract clinical and experimental context from this proteomics paper.
      This could be CLINICAL (patient samples) or LAB (cell culture/animals). Adapt accordingly.
      
      Paper: {{ input.filename }}
      {% if input.methods %}Methods: {{ input.methods }}{% endif %}
      {% if input.supplementary_information %}Supplementary: {{ input.supplementary_information }}{% endif %}
      
      Extract ALL variations of:
      - Disease: disease names (e.g., "Alzheimer's disease", "AD", "breast cancer", "lung squamous cell carcinoma", "LSCC")
      - DiseaseTreatment: disease treatments (e.g., "chemotherapy", "immunotherapy", "drug name")
      - CellLine: cell line names (e.g., "HeLa", "HEK293", "MCF7", "A549")
      - CellType: cell types - CONVERT IHC markers to cell types (e.g., "CD8+"→"CD8+ T cells"/"T cells", "CD20+"→"CD20+ B cells"/"B cells", "CD33+"→"neutrophils", "intratumoral neutrophils"→"neutrophils")
      - CellPart: cellular components (e.g., "nucleus", "cytoplasm", "mitochondria", "membrane")
      - Treatment: experimental treatments (e.g., "drug treatment", "LPS stimulation", "starvation")
      - SampleTreatment: sample processing (e.g., "FFPE", "fresh frozen", "snap frozen", "fixed")
      - Staining: staining methods (e.g., "Coomassie", "silver stain", "H&E")
      - GrowthRate: growth conditions (e.g., "exponential phase", "OD600 = 0.6")
      - SamplingTime: time points (e.g., "ZT6", "day 1", "T0", "T24")
      - BMI: body mass index (e.g., "BMI 25-30", "BMI > 30", "obese")
      - AnatomicSiteTumor: tumor anatomical location (e.g., "primary tumor", "left lobe")
      - OriginSiteDisease: disease origin site (e.g., "primary site", "tissue of origin")
      - TumorCellularity: tumor cellularity (e.g., "80%", ">70% tumor cells", "tumor purity")
      - TumorGrade: tumor grade (e.g., "Grade 1-4", "well-differentiated", "poorly differentiated", "low-grade", "high-grade")
      - TumorStage: tumor stage (e.g., "Stage I-IV", "T1-4", "N0-3", "M0-1", "TNM", "AJCC")
      - TumorSize: tumor size (e.g., "2 cm", "5 cm diameter")
      - TumorSite: tumor site (e.g., "primary site", "metastatic lesion", "lymph node metastasis")
      
      CRITICAL: When you see IHC markers (CD8, CD20, CD33, CD4, CD68, Pan-CK), convert them to cell types.
      Extract BOTH full names AND abbreviations.
      Return JSON only, no markdown. Empty list if field not found.
    
    gleaning:
      num_rounds: 2
      validation_prompt: |
        Check if extraction missed:
        For CLINICAL studies: (1) disease with full name+abbreviation, (2) tumor stage/grade/cellularity, (3) IHC markers converted to cell types (CD8→T cells, CD20→B cells, CD33→neutrophils)
        For LAB studies: (1) cell lines with variations, (2) experimental treatments, (3) cell types
        Common mistakes: IHC markers not converted to cell types, tumor staging missed, disease abbreviation without full name
        Return: {"passes_validation": true/false, "critical_omissions": [...], "suggestions": [...]}

  - name: unnest_diseases
    type: unnest
    unnest_key: Disease
    keep_empty: true

  - name: resolve_diseases
    type: resolve
    blocking_keys:
      - Disease
    blocking_threshold: 0.70
    comparison_model: gpt-4o-mini
    comparison_prompt: |
      Are these the same disease?
      Disease 1: "{{ input1.Disease }}"
      Disease 2: "{{ input2.Disease }}"
      
      Equivalences: "Alzheimer's disease"="AD", "Parkinson's"="PD", "type 2 diabetes"="T2D"="T2DM", "breast cancer"="breast carcinoma", "lung squamous cell carcinoma"="LSCC"
      Different: type 1≠type 2 diabetes, breast≠lung cancer, Alzheimer's≠Parkinson's, adenocarcinoma≠squamous cell carcinoma
      Return "True" if same disease, "False" if different.
    
    embedding_model: text-embedding-3-small
    resolution_model: gpt-4o-mini
    resolution_prompt: |
      Standardize these diseases (prefer full name with abbreviation):
      {% for entry in inputs %}{{ entry.Disease }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Examples: ["Alzheimer's disease","AD"]→"Alzheimer's disease (AD)", ["type 2 diabetes","T2D"]→"type 2 diabetes (T2D)", ["lung squamous cell carcinoma","LSCC"]→"lung squamous cell carcinoma (LSCC)"
      Return ONLY the canonical name.
    
    output:
      schema:
        canonical_disease: string

  - name: unnest_cell_lines
    type: unnest
    unnest_key: CellLine
    keep_empty: true

  - name: resolve_cell_lines
    type: resolve
    blocking_keys:
      - CellLine
    blocking_threshold: 0.75
    comparison_model: gpt-4o-mini
    comparison_prompt: |
      Are these the same cell line?
      Cell Line 1: "{{ input1.CellLine }}"
      Cell Line 2: "{{ input2.CellLine }}"
      
      Equivalences: "HEK293"="HEK 293"="HEK-293", "MCF7"="MCF-7", "A549"="A-549", "RAW264.7"="RAW 264.7"
      Different: HEK293≠HEK293T, MCF7≠MCF10A
      Return "True" if same cell line, "False" if different.
    
    embedding_model: text-embedding-3-small
    resolution_model: gpt-4o-mini
    resolution_prompt: |
      Standardize these cell lines (use common notation, maintain critical distinctions):
      {% for entry in inputs %}{{ entry.CellLine }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Examples: ["HEK293","HEK 293"]→"HEK293", ["HEK293T","HEK 293T"]→"HEK293T", ["MCF7","MCF-7"]→"MCF-7", ["A549","A-549"]→"A549"
      Return ONLY the canonical name.
    
    output:
      schema:
        canonical_cell_line: string

  - name: unnest_cell_types
    type: unnest
    unnest_key: CellType
    keep_empty: true

  - name: resolve_cell_types
    type: resolve
    blocking_keys:
      - CellType
    blocking_threshold: 0.80
    comparison_model: gpt-4o-mini
    comparison_prompt: |
      Are these the same cell type?
      Type 1: "{{ input1.CellType }}"
      Type 2: "{{ input2.CellType }}"
      
      Equivalences: "T cells"="T-cells"="T lymphocytes", "CD8+ T cells"="CD8 T cells", "CD20+ B cells"="CD20 B cells"="B cells", "macrophages"="macrophage", "neurons"="neuronal cells"
      Return "True" if same cell type, "False" if different.
    
    embedding_model: text-embedding-3-small
    resolution_model: gpt-4o-mini
    resolution_prompt: |
      Standardize these cell types (prefer specific form with markers):
      {% for entry in inputs %}{{ entry.CellType }}{% if not loop.last %}, {% endif %}{% endfor %}
      
      Examples: ["CD8+ T cells","CD8 T cells","T cells"]→"CD8+ T cells", ["B cells","CD20+ B cells"]→"CD20+ B cells", ["macrophages","macrophage"]→"macrophages"
      Return ONLY the canonical name.
    
    output:
      schema:
        canonical_cell_type: string

  - name: aggregate_clinical_data
    type: reduce
    reduce_key:
      - filename
    output:
      schema:
        unique_diseases: list[string]
        unique_cell_lines: list[string]
        unique_cell_types: list[string]
        unique_treatments: list[string]
        tumor_stages: list[string]
        tumor_grades: list[string]
        tumor_cellularity: list[string]
        tumor_sizes: list[string]
        tumor_sites: list[string]
        sample_treatments: list[string]
        staining_methods: list[string]
    prompt: |
      Aggregate and deduplicate clinical/experimental data for: {{ reduce_key.filename }}
      
      Diseases: {% for doc in inputs %}{% if doc.canonical_disease %}{{ doc.canonical_disease }}, {% endif %}{% endfor %}
      Cell lines: {% for doc in inputs %}{% if doc.canonical_cell_line %}{{ doc.canonical_cell_line }}, {% endif %}{% endfor %}
      Cell types: {% for doc in inputs %}{% if doc.canonical_cell_type %}{{ doc.canonical_cell_type }}, {% endif %}{% endfor %}
      Treatments: {% for doc in inputs %}{% for t in doc.Treatment %}{{ t }}, {% endfor %}{% endfor %}
      Tumor stages: {% for doc in inputs %}{% for s in doc.TumorStage %}{{ s }}, {% endfor %}{% endfor %}
      Tumor grades: {% for doc in inputs %}{% for g in doc.TumorGrade %}{{ g }}, {% endfor %}{% endfor %}
      Tumor cellularity: {% for doc in inputs %}{% for c in doc.TumorCellularity %}{{ c }}, {% endfor %}{% endfor %}
      
      Return deduplicated JSON with unique canonical values for all fields.

pipeline:
  steps:
    - name: clinical_experimental_pipeline
      input: papers
      operations:
        - extract_clinical_info
        - unnest_diseases
        - resolve_diseases
        - unnest_cell_lines
        - resolve_cell_lines
        - unnest_cell_types
        - resolve_cell_types
        - aggregate_clinical_data

  output:
    type: file
    path: ./output/clinical_experimental_complete.json
    intermediate_dir: ./checkpoints